# Generated by Django 2.2.10 on 2020-03-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200312_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='R123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dede', models.BigIntegerField()),
            ],
        ),
    ]
